name: Checks
on:
  pull_request:

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18
      - name: Restore node_modules cache
        uses: actions/cache@v2.1.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: All tests
        run: npm run test
      - name: Linting
        run: npm run lint
      - name: TypeCheck
        run: npm run type-check
