name: Types

# Defines when the action should be triggered
on:
  pull_request:

# Jobs to be run
jobs:
  build-and-test:
    # Virtual environment
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out your repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8

      # Setup Node.js environment and cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      # Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Run type checking
      - name: Run Typecheck
        run: pnpm run type-check
